export enum ExpenseCategoryEnum {
    MORTGAGE_OR_RENT = "MORTGAGE_OR_RENT",
    TRANSPORTATION = "TRANSPORTATION",
    FOOD = "FOOD",
    UTILITIES = "UTILITIES",
    CLOTHING = "CLOTHING",
    MEDICAL_HEALTHCARE = "MEDICAL_HEALTHCARE",
    INSURANCE = "INSURANCE",
    PERSONAL = "PERSONAL",
    DEBT = "DEBT",
    RETIREMENT = "RETIREMENT",
    EDUCATION = "EDUCATION",
    SAVINGS = "SAVINGS",
    GIFT_OR_DONATION = "GIFT_OR_DONATION",
    ENTERTAINMENT = "ENTERTAINMENT"
}